name: Matrix-Build

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        #platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [ windows-latest]
    runs-on: ${{ matrix.platform }}
    
    steps:
    
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code to a GOPATH compatible directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/github.com/alyarctiq/actions-go-acme
        
    - name: dir
      run: dir
      
#    - name: Get dependencies
#      run: |
#        go get -v -t -d ./...
#        if [ -f Gopkg.toml ]; then
#            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
#            dep ensure
#        fi
#      env:
#        GOPATH: /home/runner/work/actions-go-acme/go 

    - name: Build/Test
      #run: go build -v ./...
      run: go build -v .
      env:
        GOPATH: /home/runner/work/actions-go-acme/go 
